// Shared by structure.test.ts and pseudocode.test.ts so both drive the same branches.
// Every input runs on the fresh seed; branches that need a prior state (Send after Discover,
// Break link on a route) are covered by each topic's own operations.test.ts.
export const INPUTS: Record<string, unknown[]> = {
  'multihop/link-etx': ['C D 0.8 0.5', 'C D 0 0.5', 'A D 0.8 0.5', 'C D 2 0.5', 'nonsense'],
  'proactive-routing/advertise': ['M4', 'M2', 'X9', ''],
  'proactive-routing/move': ['M3 M6', 'M1 M5', 'M3', 'M3 M3'],
  'reactive-routing/discover-aodv': ['S D', 'S', 'S S'],
  'reactive-routing/discover-dsr': ['S D', 'X Y'],
  'reactive-routing/send-aodv': ['S D', 'bad'],
  'reactive-routing/send-dsr': ['S D'],
  'reactive-routing/break-link': ['C D', 'A E', 'S B'],
  'broadcast/select-mpr': ['A', 'C', 'X'],
  'broadcast/broadcast-mpr': ['A', 'C', ''],
  'broadcast/broadcast-flooding': ['A', 'nonsense'],
  'broadcast/remove-link': ['D F', 'A G', 'D'],
  'geographic-routing/route': ['S D', 'F D', 'D S', 'S', 'S X'],
  'clustering/leave': ['9', '5', '42', ''],
  'clustering/join': ['7 6 8', '9 6', '7 99', '7', 'x'],
  'address-allocation/join-buddy': ['D C', 'A C', 'D X', 'nonsense'],
  'address-allocation/join-qdad': ['D C', 'D'],
  'address-allocation/leave-buddy': ['C', 'B', 'X'],
  'address-allocation/crash-buddy': ['C', ''],
  'mobility/advance-rwp': [3, 0, 41],
  'mobility/advance-rpgm': [3, 2.5],
  'evaluation/metrics': [3, 0, 11],
  'qos-routing/path-bandwidth': ['A E 3', 'A E 7', 'A E', 'A E x'],
  'qos-routing/path-etx': ['A E', 'A'],
  'qos-routing/path-energy': ['A E', 'B D'],
  'qos-routing/path-hop': ['A E', 'E E'],
  'qos-routing/send': [5, 0, 51],
  'routing-attacks/send': [3, 0, 21],
  'routing-attacks/watchdog': [5, 21],
}
