// SPEC.md §19.2 quiz. Explanations cite the week reference; predict questions run on the seed.
import type { QuizQuestion } from '@/types/case-study'

export const campQuiz: QuizQuestion[] = [
  {
    kind: 'choice',
    id: 'camp-dhcp',
    prompt: 'Why does a DHCP server not fit the relief camp?',
    choices: [
      'DHCP addresses are too short for a camp.',
      'Stateful allocation needs a server, and with a changing topology the server may be unreachable.',
      'DHCP cannot hand out more than 9 addresses.',
      'DHCP needs GPS on every radio.',
    ],
    answer: 1,
    explanation: 'Week 4: stateful allocation needs a server, but the topology keeps changing and a central server may be unreachable (Misra p. 337).',
    topicSlug: 'address-allocation',
  },
  {
    kind: 'choice',
    id: 'camp-crash',
    prompt: 'Under Buddy, what is lost when a radio vanishes without saying goodbye?',
    choices: [
      'Nothing: its neighbor already holds a copy of its pool.',
      'Every address in the camp, so all radios must start over.',
      'The pool it held, which goes with it until the nodes synchronize.',
      'Only its cluster head.',
    ],
    answer: 2,
    explanation: 'Week 4: a node that vanishes suddenly takes its pool with it, so nodes need periodic synchronization (Misra pp. 338-339).',
    topicSlug: 'address-allocation',
  },
  {
    kind: 'choice',
    id: 'camp-gateway',
    prompt: 'After Elect on the seed camp, which of these radios is a gateway?',
    choices: ['4', '3', '1', '6'],
    answer: 3,
    explanation: 'Week 4: a node connected to two or more cluster heads becomes a gateway (Misra pp. 31-32). Radio 6 hears heads 9 and 8; 4, 3, and 1 each hear one head.',
    topicSlug: 'clustering',
  },
  {
    kind: 'choice',
    id: 'camp-rpgm',
    prompt: 'Why does RPGM fit volunteer teams better than random waypoint?',
    choices: [
      'Team members move around a shared reference point, as the volunteers do.',
      'RPGM never moves any node.',
      'RPGM is faster to compute.',
      'Random waypoint cannot place more than eight nodes.',
    ],
    answer: 0,
    explanation: 'Week 5: in RPGM a group model moves the group’s center and each member moves within a disc around it; group models fit real groups such as SAR teams (Misra pp. 244-245).',
    topicSlug: 'mobility',
  },
  {
    kind: 'choice',
    id: 'camp-vmin',
    prompt: 'A random waypoint run sets the minimum speed vmin to zero. What goes wrong?',
    choices: [
      'Nodes leave the area.',
      'Nodes can pick a very small speed, and the average speed keeps falling.',
      'Every node stops at once.',
      'The pause time becomes negative.',
    ],
    answer: 1,
    explanation: 'Week 5: with vmin at zero, nodes can choose a very small speed and the average speed keeps falling; the fix is to bound vmin (Misra p. 241). This simulator draws speeds from 0.3 up.',
    topicSlug: 'mobility',
  },
  {
    kind: 'choice',
    id: 'camp-report',
    prompt: 'What must a simulation report of the camp include so someone else can repeat it?',
    choices: [
      'Only the best run.',
      'The mean delivery ratio, rounded to a whole number.',
      'A screenshot of the canvas.',
      'The scenario, every parameter, the seeds and number of runs, and results with their spread.',
    ],
    answer: 3,
    explanation: 'Week 6: a report gives the network model, the scenario, the simulator parameters, the replications and seeds, and metrics with their spread (Loo pp. 60 and 81-82; Misra pp. 22 and 272-273).',
    topicSlug: 'evaluation',
  },
  {
    kind: 'predict',
    id: 'camp-predict-join',
    prompt: 'Volunteer joins with 10 1. Volunteer 10 arrives next to 1 and hears 1, 7, and 5, nearest first. Radio 1 holds only its own address. What happens next?',
    choices: [
      '1 splits its range and gives half to 10.',
      '10 picks a random address and asks the camp.',
      '1 has no spare address, so 10 asks the next neighbor.',
      '10 becomes a cluster head at once.',
    ],
    answer: 2,
    explanation: 'Week 4: a Buddy node can only give away half of what it holds, and 1 holds one address. The space was used unevenly where people arrived (Misra pp. 338-339).',
    topicSlug: 'address-allocation',
    operationId: 'join',
    variant: 'rpgm',
    input: '10 1',
    stepIndex: 0,
    expect: '1 has no spare address',
  },
  {
    kind: 'predict',
    id: 'camp-predict-elect',
    prompt: 'Elect cluster heads. 9 has the highest id among its undecided neighbors 4, 2, and 6, so it becomes a cluster head. What happens next?',
    choices: [
      '8 becomes a cluster head.',
      '4 joins cluster head 9.',
      '6 becomes a gateway.',
      '9 gives up its head role to 6.',
    ],
    answer: 1,
    explanation: 'Week 4: the undecided neighbors of a new head join its cluster, in order (Misra pp. 31-32). 4 is the first of them.',
    topicSlug: 'clustering',
    operationId: 'elect',
    variant: 'rpgm',
    input: null,
    stepIndex: 0,
    expect: '4 joins cluster head 9',
  },
]
