// SPEC.md §10.3 listings in the §7.1 Python style. One listing per operation id; AODV and DSR are
// separate ids because their listings differ (SPEC §7 `variants`).
export const reactivePseudocode: Record<string, string[]> = {
  'discover-aodv': [
    'def discover(src, dst):',
    '    src.request_id += 1',
    '    rreq = RREQ(src, src.request_id, dst)',
    '    queue = deque([src])',
    '    while queue:',
    '        v = queue.popleft()',
    '        v.broadcast(rreq)',
    '        for n in v.neighbors():',
    '            if (src, rreq.request_id) in n.seen:',
    '                continue  # drop the duplicate copy',
    '            n.seen.add((src, rreq.request_id))',
    '            n.reverse[src] = v  # the reverse path',
    '            if n == dst:',
    '                continue  # dst answers instead of forwarding',
    '            queue.append(n)',
    '    w = dst',
    '    while w != src:  # the RREP retraces the reverse path',
    '        prev = w.reverse[src]',
    '        w.send(RREP(dst), to=prev)',
    '        prev.route[dst] = w',
    '        w = prev',
  ],
  'discover-dsr': [
    'def discover(src, dst):',
    '    src.request_id += 1',
    '    queue = deque([(src, [src])])',
    '    candidates = []',
    '    while queue:',
    '        v, record = queue.popleft()',
    '        v.broadcast(RREQ(src, src.request_id, dst, record))',
    '        for n in v.neighbors():',
    '            if n in record or (n != dst and (src, src.request_id) in n.seen):',
    '                continue  # drop the copy',
    '            n.seen.add((src, src.request_id))',
    '            record_n = record + [n]  # the route record grows',
    '            if n == dst:',
    '                candidates.append(record_n)',
    '            else:',
    '                queue.append((n, record_n))',
    '    route = min(candidates, key=len)  # the first to arrive wins a tie',
    '    send_along(reversed(route), RREP(route))',
    '    src.cache[dst] = route',
  ],
  'send-aodv': [
    'def send(src, dst, payload):',
    '    if dst not in src.route:',
    '        return False  # run discover(src, dst) first',
    '    v = src',
    '    while v != dst:',
    '        nxt = v.route[dst]  # each node looks up its own table',
    '        v.send(DATA(dst, payload), to=nxt)',
    '        v = nxt',
    '    return True',
  ],
  'send-dsr': [
    'def send(src, dst, payload):',
    '    if dst not in src.cache:',
    '        return False  # run discover(src, dst) first',
    '    packet = DATA(dst, payload, route=src.cache[dst])  # the header carries the route',
    '    v = src',
    '    while v != dst:',
    '        nxt = packet.route[packet.route.index(v) + 1]',
    '        v.send(packet, to=nxt)',
    '        v = nxt',
    '    return True',
  ],
  'break-link': [
    'def break_link(net, u, v):',
    '    net.link(u, v).broken = True',
    '    for end in (u, v):',
    '        for node in end.rerr_path():  # toward the route end on its side',
    '            node.delete_routes_through(u, v)',
    "    return  # src's next discover() uses a new request_id",
  ],
}

/** Line numbers the operations highlight, per listing. */
export const L = {
  discover: {
    aodv: { def: 1, request: 2, loop: 5, broadcast: 7, drop: 10, first: 12, arrived: 14, rrep: 20 },
    dsr: { def: 1, request: 2, loop: 5, broadcast: 7, drop: 10, first: 12, arrived: 14, pick: 17, rrep: 18, cache: 19 },
  },
  send: {
    aodv: { def: 1, no_route: 3, lookup: 6, forward: 7, done: 9 },
    dsr: { def: 1, no_route: 3, lookup: 7, forward: 8, done: 10 },
  },
  breakLink: { def: 1, mark: 2, loop: 3, rerr: 4, remove: 5, done: 6 },
} as const
