// SPEC.md §19.1 quiz. Explanations cite the week reference; predict questions run on the seed.
import type { QuizQuestion } from '@/types/case-study'

export const sarQuiz: QuizQuestion[] = [
  {
    kind: 'choice',
    id: 'sar-relay',
    prompt: 'Why must a relay radio on the slope forward reports that are not its own?',
    choices: [
      'Because the gateway asks it to by name.',
      'Because there is no access point: every node is both host and router.',
      'Because forwarding saves its battery.',
      'Because only relays may send RREQs.',
    ],
    answer: 1,
    explanation: 'Week 1: in an ad hoc network nodes communicate without a central administrator, and each node works as both a host and a router (Loo p. 5).',
    topicSlug: 'multihop',
  },
  {
    kind: 'choice',
    id: 'sar-reactive',
    prompt: 'The team sends a report every half hour or so. Which kind of routing protocol fits that traffic better?',
    choices: [
      'Proactive, because routes are always available.',
      'Proactive, because its control overhead is low.',
      'Reactive, because its overhead is low and it pays only when a report needs a route.',
      'Neither: the radios need a fixed route table typed in by hand.',
    ],
    answer: 2,
    explanation: 'Week 2: reactive protocols have low communication overhead and a discovery delay; proactive ones have high overhead that runs even with no data (Loo Table 2.1, p. 23).',
    topicSlug: 'reactive-routing',
  },
  {
    kind: 'choice',
    id: 'sar-mpr-cost',
    prompt: 'What does MPR relaying save on the slope, and what does it give up?',
    choices: [
      'It saves transmissions and duplicates, and gives up some of the reliability that repetition brings.',
      'It saves route length, and gives up the reverse path.',
      'It saves nothing on this slope, because every radio still relays.',
      'It saves battery at G, and gives up the RREP.',
    ],
    answer: 0,
    explanation: 'Week 3: only the MPRs forward a broadcast, which cuts redundant rebroadcasts (Misra pp. 126-127), while blind flooding is more reliable precisely because every node repeats the packet (Misra pp. 139-142).',
    topicSlug: 'broadcast',
  },
  {
    kind: 'choice',
    id: 'sar-cut',
    prompt: 'Which of these radios is an articulation point on the seed slope?',
    choices: ['R2', 'R3', 'T3', 'R5'],
    answer: 3,
    explanation: 'Week 1: an articulation point is a node whose removal increases the number of components (Misra Definition 1.4). Without R5, G is cut off from everyone; R2, R3, and T3 each have a way around them.',
    topicSlug: 'multihop',
  },
  {
    kind: 'choice',
    id: 'sar-rrep',
    prompt: 'Which way does G send the RREP back to T1?',
    choices: [
      'By flooding it, so every radio learns the route.',
      'Straight to T1 over one long hop.',
      'Along the reverse path that the first RREQ copies recorded.',
      'Along the path with the most relays, to spread the load.',
    ],
    answer: 2,
    explanation: 'Week 2: in AODV a node records the neighbor its first RREQ copy came from, and the destination answers as unicast along that reverse path.',
    topicSlug: 'reactive-routing',
  },
  {
    kind: 'choice',
    id: 'sar-flood-reliable',
    prompt: 'Why is blind flooding more reliable than MPR relaying?',
    choices: [
      'It uses RTS/CTS for every broadcast.',
      'Every node repeats the packet, so one lost copy is usually covered by another.',
      'It picks the shortest route first.',
      'It never causes collisions.',
    ],
    answer: 1,
    explanation: 'Week 3: blind flooding is more reliable precisely because every node repeats the packet, while the reliability of optimized broadcast drops under background traffic (Misra pp. 139-142).',
    topicSlug: 'broadcast',
  },
  {
    kind: 'predict',
    id: 'sar-predict-t3',
    prompt:
      'MPR relays, Discover route to base from T1. T1 chose only T2 as its MPR. T2 has relayed, and R1 has recorded T2 as its way back. T3 heard the RREQ first from T1 and is next in the queue. What happens next?',
    choices: [
      'T3 transmits the RREQ to its neighbors.',
      'T3 is not an MPR of T1, so it does not relay.',
      'T3 sends an RREP to T1.',
      'T3 records R1 as its way back to T1.',
    ],
    answer: 1,
    explanation: 'Week 3: a node relays a broadcast only for a neighbor that chose it as an MPR (Misra pp. 126-127). T1 chose T2, so T3 stays silent.',
    topicSlug: 'broadcast',
    operationId: 'discover-mpr',
    variant: 'mpr',
    input: 'T1',
    stepIndex: 7,
    expect: 'is not an MPR of T1',
  },
  {
    kind: 'predict',
    id: 'sar-predict-r5',
    prompt: 'R5 has just walked out of range of every radio. What does the next step say?',
    choices: [
      'The team can still reach G another way.',
      'R4 sends an RERR toward T1.',
      'R5 was an articulation point: without it the team has no path to G.',
      'G moves next to R4.',
    ],
    answer: 2,
    explanation: 'Week 1: R5 is the only radio between R4 and G, so removing it splits the network (Misra Definition 1.4).',
    topicSlug: 'multihop',
    operationId: 'walk-away',
    variant: 'mpr',
    input: 'R5',
    stepIndex: 1,
    expect: 'was an articulation point',
  },
]
