// SPEC.md §19.3 quiz. Explanations cite the week reference; predict questions run on the seed, so
// they ask about Find route; the watchdog moments, which need M joined first, are choice questions.
import type { QuizQuestion } from '@/types/case-study'

export const meshQuiz: QuizQuestion[] = [
  {
    kind: 'choice',
    id: 'mesh-fewer-hops',
    prompt: 'Why can a route with fewer hops be the slower one?',
    choices: [
      'Fewer hops means longer hops, and link quality falls with distance, so more tries are lost.',
      'Every hop adds a fixed delay that grows with the hop count.',
      'Routers on short routes have smaller batteries.',
      'A short route cannot carry ACKs.',
    ],
    answer: 0,
    explanation: 'Week 7: fewer hops means longer hops, and link quality falls with distance; ETX routes take more hops and still get better TCP throughput (Misra pp. 368-369).',
    topicSlug: 'qos-routing',
  },
  {
    kind: 'choice',
    id: 'mesh-etx',
    prompt: 'A link delivers 0.5 of the frames one way and 0.5 of the ACKs back. What is its ETX?',
    choices: ['0.25', '1', '2', '4'],
    answer: 3,
    explanation: 'Week 1 and Week 7: ETX is one divided by the product of the delivery ratios in both directions, so 1 / (0.5 × 0.5) = 4 (Misra Definitions 1.5 and 1.6).',
    topicSlug: 'qos-routing',
  },
  {
    kind: 'choice',
    id: 'mesh-black-hole',
    prompt: 'What does a black hole do?',
    choices: [
      'It tunnels routing messages to a distant part of the network.',
      'It claims a route to the destination, attracts the data, and drops every packet without a trace.',
      'It floods the network with junk routing messages.',
      'It forwards every packet but reads them first.',
    ],
    answer: 1,
    explanation: 'Week 8: M claims to have a route to D, so S sends its data through M, and M drops every packet without a trace (Misra pp. 460-461).',
    topicSlug: 'routing-attacks',
  },
  {
    kind: 'choice',
    id: 'mesh-gray-hole',
    prompt: 'Why is a gray hole harder to detect than a black hole?',
    choices: [
      'It only drops routing messages.',
      'It changes its address every packet.',
      'It drops only part of the traffic, so its failures look like ordinary losses.',
      'It never joins a route.',
    ],
    answer: 2,
    explanation: 'Week 8: the gray hole variant drops only part of the traffic, which makes it harder to detect (Misra pp. 460-461).',
    topicSlug: 'routing-attacks',
  },
  {
    kind: 'choice',
    id: 'mesh-watchdog-wrong',
    prompt: 'In which situation can the watchdog accuse an honest router?',
    choices: [
      'When the honest router forwards too fast.',
      'When a collision hides the honest router’s forward from the listener.',
      'When the source uses ETX.',
      'When the honest router has more than two neighbors.',
    ],
    answer: 1,
    explanation: 'Week 8: ambiguous collisions or collisions at the receiver hide a forward from the listener, and a node can falsely accuse another (Misra pp. 444-446).',
    topicSlug: 'routing-attacks',
  },
  {
    kind: 'choice',
    id: 'mesh-fourth-failure',
    prompt: 'M has joined and S sends through it with the watchdog on. S has just counted M’s fourth failure. What happens next?',
    choices: [
      'S keeps sending through M until the tenth failure.',
      'M is reported, and the pathrater switches S to S, A, B, C, D.',
      'D sends an RERR to S.',
      'S floods a new RREQ.',
    ],
    answer: 1,
    explanation: 'Week 8: when the failure count passes the threshold, the node is reported and the pathrater avoids it (Misra pp. 444-445). This demo’s threshold is 3, so the fourth failure triggers the report.',
    topicSlug: 'routing-attacks',
  },
  {
    kind: 'predict',
    id: 'mesh-predict-etx',
    prompt: 'ETX with watchdog, Find route before M joins. The candidates are S, X, D (2 hops, ETX 8.00) and S, A, B, C, D (4 hops, ETX 4.43). What happens next?',
    choices: [
      'S, X, D has the fewest hops, so S uses it.',
      'S, A, B, C, D has the smallest ETX, 4.43, so S uses it.',
      'S floods the RREQ again.',
      'S uses both routes in turn.',
    ],
    answer: 1,
    explanation: 'Week 7: ETX routes take more, shorter hops (Misra pp. 368-369). Four links at 0.95 cost less than two at 0.5.',
    topicSlug: 'qos-routing',
    operationId: 'route',
    variant: 'etx-watchdog',
    input: null,
    stepIndex: 9,
    expect: 'has the smallest ETX',
  },
  {
    kind: 'predict',
    id: 'mesh-predict-hop',
    prompt: 'Hop count, Find route before M joins, with the same two candidates. What happens next?',
    choices: [
      'S, A, B, C, D has the smallest ETX, so S uses it.',
      'S drops both candidates.',
      'S, X, D has the fewest hops, so S uses it.',
      'S waits for a third RREP.',
    ],
    answer: 2,
    explanation: 'Hop count compares only the number of hops, so the two weak links win (Week 7, Misra pp. 368-369).',
    topicSlug: 'qos-routing',
    operationId: 'route',
    variant: 'hop',
    input: null,
    stepIndex: 9,
    expect: 'S, X, D has the fewest hops',
  },
]
